# Change these first
owner: yorkyang2333 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: My Site
    url: https://yorkyang2333.top
  - name: Apple
    url: https://www.apple.com
  - name: Google
    url: https://www.google.com
  - name: GitHub
    url: https://github.com
  - name: Microsoft
    url: https://microsoft.com
  - name: Vercel
    url: https://vercel.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yorkyang2333.top
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/yorkyang2333.png
  name: Are my sites down?
  introTitle: "Are my sites down?"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://yorkyang2333.top
    - title: GitHub
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
